services:
  django:
    container_name: django
    image: django:1
    build: ./srcs/django/
    depends_on:
      postgresql:
        condition: service_healthy
    # ports:
    #   - '8000:8000'
    volumes:
      - django_volume:/project
      - frontend_volume:/var/www/html
    env_file:
      - .env
    networks:
      - transcendence
    # restart: always

  postgresql:
    container_name: postgresql
    image: postgresql:1
    build: ./srcs/postgresql/
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
    # ports:
    #   - '5432:5432'
    env_file:
      - .env
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    # restart: always

  nginx:
    container_name: nginx
    image: nginx:1
    build: ./srcs/nginx/
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - frontend_volume:/var/www/html
    env_file:
      - .env
    depends_on:
      - django
    networks:
      - transcendence
    # restart: always

  frontend:
    container_name: frontend
    image: frontend:1
    build: ./srcs/frontend/
    networks:
      - transcendence
    volumes:
      - frontend_volume:/var/www/html
    depends_on:
      - django
    # restart: always

volumes:
  django_volume:
    name: django_volume
    driver: local
    driver_opts:
      type : none
      device: /home/user/ecole_42/transcendence/data/django_volume
      # device: /Users/yuuuuki/ecole_42/transcendence/data/django_volume
      o : bind
  postgresql_volume:
    name: postgresql_volume
    driver: local
    driver_opts:
      type : none
      device: /home/user/ecole_42/transcendence/data/postgresql_volume
      # device: /Users/yuuuuki/ecole_42/transcendence/data/postgresql_volume
      o : bind

  frontend_volume:
    name: frontend_volume
    driver: local
    driver_opts:
      type : none
      device: /home/user/ecole_42/transcendence/data/frontend_volume
      # device: /Users/yuuuuki/ecole_42/transcendence/data/frontend_volume
      o : bind

networks:
  transcendence:
    driver: bridge
